<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContractTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $exists = DB::table('contract_templates')->where('is_default', true)->first(); if ($exists) { echo 'Ya existe'; return; } $templateId = DB::table('contract_templates')->insertGetId([
            'nombre'        => 'Contrato de Administración de Inmueble — Serviarrendar S.A.S',
            'tipo_contrato' => 'administracion_arriendo',
            'encabezado'    => 'CONTRATO DE ADMINISTRACION DE INMUEBLE',
            'is_active'     => true,
            'is_default'    => true,
            'created_at'    => now(),
            'updated_at'    => now(),
        ]);

        $clausulas = [
            [
                'numero' => 'PRIMERO',
                'titulo' => 'Partes del Contrato',
                'tipo'   => 'clausula',
                'orden'  => 1,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'Confiero a la sociedad INMOBILIARIA SERVIARRENDAR SAS, con NIT 807.005.762-4 con domicilio en Ocaña y representada legalmente por YANETH DEL CARMEN PEREZ AREVALO, mayor de edad y vecina de Ocaña, identificada con la cédula de ciudadanía No. 37.321.359 expedida en Ocaña, poder para administrar por conducto de su departamento, los inmuebles que se identifican al encabezado de este documento y quien en adelante se llamara EL ADMINISTRADOR, se ha celebrado el presente Contrato De Administración De Inmueble, el cual se regirá por las disposiciones legales Art. 1973 y siguientes del Código Civil Art.515 y siguiente del código de comercio, Art 518,519,520,521,522,523 y 864 del código de comercio.',
            ],
            [
                'numero' => 'SEGUNDO',
                'titulo' => 'Objeto',
                'tipo'   => 'clausula',
                'orden'  => 2,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'A través del presente contrato EL PROPIETARIO entrega para su ADMINISTRACION, de manera real y material, AL ADMINISTRADOR el bien inmueble de su propiedad identificado en el encabezado de este documento, con todas sus especificaciones técnicas, área construida, coeficiente de copropiedad y escritura de propiedad horizontal según corresponda.',
            ],
            [
                'numero' => 'TERCERO',
                'titulo' => 'Facultades del Administrador',
                'tipo'   => 'clausula',
                'orden'  => 3,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'EL PROPIETARIO faculta al ADMINISTRADOR para: a) Anunciar y promover por medios ordinarios e idóneos el arriendo del inmueble. b) Escoger a los arrendatarios que reúnan los requisitos exigidos. c) Celebrar los contratos de arrendamiento respectivos bajo las garantías oportunas. d) Recibir los arrendamientos y demás pagos a cargo de los arrendatarios. e) Arrendar el inmueble por el precio acordado con EL PROPIETARIO. f) Otorgar autorizaciones a los arrendatarios para traslado o instalaciones de líneas de servicio telefónico. g) Efectuar todas aquellas reparaciones locativas que correspondan al PROPIETARIO. h) Dar por terminado antes del vencimiento, por justa causa, el contrato de arriendo. i) Iniciar oportunamente las acciones judiciales, administrativas y/o policivas. j) En casos de mora en las obligaciones hipotecarias, cancelar su obligación hasta el monto de los arriendos. k) Descontar de los cánones de arrendamiento el valor de la comisión y demás gastos autorizados.',
            ],
            [
                'numero' => 'CUARTA',
                'titulo' => 'Obligaciones del Administrador',
                'tipo'   => 'clausula',
                'orden'  => 4,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'El ADMINISTRADOR se compromete para con EL PROPIETARIO en: a) Ejercer la administración de las propiedades con las facultades otorgadas. b) Entregar el valor de los arrendamientos por mensualidades vencidas, el día cinco (05) día hábil del mes siguiente al que hayan pagado los arrendatarios, previa deducción de la comisión y los gastos efectuados por cuenta del PROPIETARIO. c) Rendir mensualmente estado de cuenta y liquidación de los arriendos recibidos. d) Elaborar los contratos de arrendamiento de acuerdo con las normas vigentes. e) Impulsar el arrendamiento de las propiedades por los medios ordinarios. f) Supervisar el pago de los servicios públicos y de la administración. g) Informar oportunamente al PROPIETARIO sobre gravámenes, cargas o cuotas extraordinarias. h) Visitar periódicamente el inmueble para verificar su estado de conservación.',
            ],
            [
                'numero' => 'QUINTA',
                'titulo' => 'Obligaciones del Propietario',
                'tipo'   => 'clausula',
                'orden'  => 5,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'EL PROPIETARIO asume las siguientes obligaciones: A) Reconocer a INMOBILIARIA SERVIARRENDAR SAS la remuneración por el servicio de administración y los costos bancarios del traslado del dinero. B) Reconocer los gastos que demanden las actividades tales como pagos de administración, servicios públicos, arreglos de daños y demás mejoras, el equivalente al 8% del valor. C) Cumplir con las obligaciones que impone la ley a los propietarios en calidad de arrendador. D) Autorizar a INMOBILIARIA SERVIARRENDAR SAS para abonar saldos disponibles en caso de mora en cuotas de copropiedad. E) Conocer y participar en las asambleas de copropietarios. F) En los reajustes de inmueble diferente a vivienda, autoriza a convenir un reajuste mínimo del IPC del año anterior. G) Asumir los costos judiciales en caso de terminación de contrato por causales diferentes a mora. H) Notificar por escrito cualquier cambio en el régimen tributario. I) Pagar los gastos, honorarios y costas de los procesos jurídicos atribuibles al PROPIETARIO.',
            ],
            [
                'numero' => 'PARÁGRAFO — REPARACIONES',
                'titulo' => 'Parágrafo: Reparaciones',
                'tipo'   => 'paragrafo',
                'orden'  => 6,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'En caso de que el INMUEBLE presente daños no atribuibles al mal uso del arrendatario, EL PROPIETARIO se compromete a realizar las obras tendientes a su reparación en un periodo no superior a 05 días calendario contados desde su notificación por cualquier medio electrónico o escrito. En caso de no iniciarlos en el periodo descrito, faculta a INMOBILIARIA SERVIARRENDAR SAS a iniciar los arreglos y descontar el costo de los mismos de los saldos que tuviese a su favor.',
            ],
            [
                'numero' => 'PARÁGRAFO — INTERMEDIACIÓN',
                'titulo' => 'Parágrafo: No Intervención Directa',
                'tipo'   => 'paragrafo',
                'orden'  => 7,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'El propietario no podrá notificar o intervenir de manera directa con el arrendatario. Cualquier situación deberá ser informada a INMOBILIARIA SERVIARRENDAR SAS para que sea esta última la encargada de llevar el proceso de intermediación entre las partes. Toda comunicación directa entre propietario y arrendatario sin autorización de la inmobiliaria queda nula, sin valor jurídico y se entenderá como una causal de incumplimiento del contrato de administración.',
            ],
            [
                'numero' => 'SEXTA',
                'titulo' => 'Comisión',
                'tipo'   => 'clausula',
                'orden'  => 8,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'La comisión por los servicios de arrendamiento que pacte EL ADMINISTRADOR, de acuerdo con el presente contrato será del DIEZ POR CIENTO (10%) del valor del canon mensual de arrendamiento.',
            ],
            [
                'numero' => 'SÉPTIMA',
                'titulo' => 'Fijación de Canon',
                'tipo'   => 'clausula',
                'orden'  => 9,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'El precio acordado con EL PROPIETARIO, por el cual se arrendarán los inmuebles, será el establecido al momento de la firma del presente contrato, teniendo en cuenta la calidad, ubicación del inmueble y las leyes vigentes en materia de arrendamiento, procurando el mejor beneficio para el propietario.',
            ],
            [
                'numero' => 'OCTAVA',
                'titulo' => 'Gastos de Comercialización',
                'tipo'   => 'clausula',
                'orden'  => 10,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'Los gastos de mercadeo y promoción del inmueble serán sufragados por EL ADMINISTRADOR.',
            ],
            [
                'numero' => 'NOVENA',
                'titulo' => 'Término del Contrato',
                'tipo'   => 'clausula',
                'orden'  => 11,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'El presente contrato tendrá una duración de doce (12) meses y una vez arrendado, se supeditará su iniciación, terminación y prórroga al contrato suscrito con los arrendatarios. Vencido este término, si alguna de las dos partes no lo da por terminado mediante aviso escrito comunicado con treinta (30) días de anticipación, se entenderá prorrogado por igual período. Las partes podrán darlo por terminado en cualquier tiempo de común acuerdo, notificando a la otra parte con sesenta (60) días de antelación. a) Si hubiese contratos de arrendamiento vigente y EL PROPIETARIO deseare terminarlo, pagará a EL ADMINISTRADOR la comisión por los meses que faltaren y la indemnización correspondiente. b) Si EL ADMINISTRADOR lo diera por terminado, una vez notificado y vencido el término, cesarán sus obligaciones. c) Si EL PROPIETARIO solicitare el endoso del contrato de arrendamiento vigente, este endoso se efectuará previa cancelación del 50% del valor de la comisión de arrendamiento a endosar.',
            ],
            [
                'numero' => 'PARÁGRAFO — RESPONSABILIDADES',
                'titulo' => 'Parágrafo: Responsabilidades',
                'tipo'   => 'paragrafo',
                'orden'  => 12,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'EL ADMINISTRADOR no será responsable por robo o daños que puedan ocurrir en el inmueble, ni por destrucción del inmueble por asonadas, actos de terrorismo, incendios, terremotos y demás hechos de fuerza mayor o caso fortuito.',
            ],
            [
                'numero' => 'DÉCIMA',
                'titulo' => 'Venta del Inmueble',
                'tipo'   => 'clausula',
                'orden'  => 13,
                'es_editable'   => true,
                'es_obligatoria'=> false,
                'contenido' => 'Siempre y cuando sea autorizado por el propietario, en caso de que el inmueble objeto del presente contrato fuere comprado directamente por el arrendatario, EL PROPIETARIO cancelará a EL ADMINISTRADOR el valor de la comisión de venta del TRES POR CIENTO (3%). EL ADMINISTRADOR gestionará los trámites de venta respectivos si así lo pidiere EL PROPIETARIO.',
            ],
            [
                'numero' => 'DÉCIMA PRIMERA',
                'titulo' => 'Mérito Ejecutivo',
                'tipo'   => 'clausula',
                'orden'  => 14,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'Este contrato presta mérito ejecutivo para exigir el cumplimiento de todas las obligaciones contraídas entre las partes. Las partes renuncian expresamente a los requerimientos para el pago de las obligaciones derivadas del mismo.',
            ],
            [
                'numero' => 'DÉCIMA SEGUNDA',
                'titulo' => 'Fallecimiento del Propietario',
                'tipo'   => 'clausula',
                'orden'  => 15,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'En caso de muerte de EL PROPIETARIO, EL ADMINISTRADOR suspenderá la entrega de los arrendamientos hasta tanto el Juzgado o la Notaría donde se esté tramitando la respectiva sucesión, le oficie sobre el destino de dichos valores.',
            ],
            [
                'numero' => 'DÉCIMA TERCERA',
                'titulo' => 'Cláusulas Adicionales',
                'tipo'   => 'clausula',
                'orden'  => 16,
                'es_editable'   => true,
                'es_obligatoria'=> false,
                'contenido' => 'Hace parte integral del presente contrato el Contrato de Seguro de Arrendamiento Básico, si ha sido tomado por EL PROPIETARIO.',
            ],
            [
                'numero' => 'DÉCIMA CUARTA',
                'titulo' => 'Cláusula Penal',
                'tipo'   => 'clausula',
                'orden'  => 17,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'Por la violación total o parcial de este contrato, las partes pagarán a la otra el valor de dos (2) mensualidades de arrendamiento sin necesidad de requerimiento alguno.',
            ],
            [
                'numero' => 'DÉCIMA QUINTA',
                'titulo' => 'Cesión del Contrato',
                'tipo'   => 'clausula',
                'orden'  => 18,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'El presente contrato y los derechos y deberes que de él emanan podrán cederse por EL ADMINISTRADOR, sin la autorización expresa y escrita de EL PROPIETARIO, siempre y cuando se haga a personas propietarias o vinculantes del inmueble.',
            ],
            [
                'numero' => 'DÉCIMA SEXTA',
                'titulo' => 'Cláusula Compromisoria',
                'tipo'   => 'clausula',
                'orden'  => 19,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'Cualquier diferencia que surja con ocasión de la celebración, interpretación, ejecución, terminación y liquidación del presente contrato podrá ser sometida a un tribunal de arbitramento que decidirá en derecho conforme a las leyes colombianas en un plazo no mayor a tres (3) meses. El tribunal será conformado por la notaría de Ocaña con la aprobación de las partes. Los gastos serán por cuenta de la parte vencida. No se adelantarán por este medio los procesos ejecutivos.',
            ],
            [
                'numero' => 'DÉCIMA SÉPTIMA',
                'titulo' => 'Derechos Fiscales',
                'tipo'   => 'clausula',
                'orden'  => 20,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'El valor de los derechos fiscales y demás gastos que cause el otorgamiento del presente contrato o de sus prórrogas correrá por cuenta de EL PROPIETARIO.',
            ],
            [
                'numero' => 'DÉCIMA OCTAVA',
                'titulo' => 'Formalidades',
                'tipo'   => 'clausula',
                'orden'  => 21,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'El presente contrato se suscribirá en el número de originales con destino a cada uno de las partes contratantes.',
            ],
            [
                'numero' => 'DÉCIMA NOVENA',
                'titulo' => 'Notificación',
                'tipo'   => 'clausula',
                'orden'  => 22,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'Para efectos judiciales y extrajudiciales las partes se notificarán en las siguientes direcciones: ADMINISTRADOR: Carrera 13 # 11-15 Ofc 103 Centro, Ocaña o al correo electrónico serviarrendarltda@gmail.com. EL PROPIETARIO: en la dirección registrada en el presente contrato. En caso de cambio de dirección, las partes se comprometen a informar a la otra el nuevo domicilio.',
            ],
            [
                'numero' => 'VIGÉSIMA',
                'titulo' => 'Modificaciones Escritas',
                'tipo'   => 'clausula',
                'orden'  => 23,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'Cualquier modificación que acuerden las partes deberá hacerse constar por escrito; sin dicha formalidad se reputará inexistente.',
            ],
            [
                'numero' => 'VIGÉSIMA PRIMERA',
                'titulo' => 'Derecho de Retención',
                'tipo'   => 'clausula',
                'orden'  => 24,
                'es_editable'   => false,
                'es_obligatoria'=> true,
                'contenido' => 'La sociedad mandataria tendrá derecho a retener la administración de los inmuebles y los productos causados mientras exista cargo del mandante y a favor de la Sociedad Mandataria, saldo alguno por causa de este cargo o por cualquier otro motivo proveniente de obligaciones contractuales, sin perjuicio de iniciar la acción ejecutiva correspondiente.',
            ],
            [
                'numero' => 'VIGÉSIMA SEGUNDA',
                'titulo' => 'Domicilio',
                'tipo'   => 'clausula',
                'orden'  => 25,
                'es_editable'   => true,
                'es_obligatoria'=> true,
                'contenido' => 'Para todos los efectos legales el domicilio contractual será la Ciudad de Ocaña, Norte de Santander, Colombia.',
            ],
        ];

        foreach ($clausulas as $clausula) {
            DB::table('contract_clauses')->insert([
                'contract_template_id' => $templateId,
                'numero'        => $clausula['numero'],
                'titulo'        => $clausula['titulo'],
                'tipo'          => $clausula['tipo'],
                'contenido'     => $clausula['contenido'],
                'es_editable'   => $clausula['es_editable'],
                'es_obligatoria'=> $clausula['es_obligatoria'],
                'orden'         => $clausula['orden'],
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ]);
        }
    }
}
