<?php
namespace Database\Seeders;

use App\Models\ContractTemplate;
use App\Models\ContractClause;
use Illuminate\Database\Seeder;

class RentalContractTemplateSeeder extends Seeder
{
    public function run(): void
    {
        // ── VIVIENDA URBANA ──────────────────────────────────
        $vivienda = ContractTemplate::create([
            'nombre'        => 'Contrato de Arrendamiento Vivienda Urbana — Serviarrendar S.A.S',
            'tipo_contrato' => 'arrendamiento_vivienda',
            'is_default'    => true,
            'is_active'     => true,
        ]);

        $clausulasVivienda = [
            ['numero'=>'PRIMERA',         'titulo'=>'Objeto del contrato',       'orden'=>1,  'contenido'=>'Mediante el presente contrato el ARRENDADOR concede al ARRENDATARIO el goce del inmueble que adelante se identifica por su dirección, de acuerdo con el inventario que las partes firman por separado.'],
            ['numero'=>'SEGUNDA',         'titulo'=>'Destinación',               'orden'=>2,  'contenido'=>'EL ARRENDATARIO se obliga a usar el inmueble para la VIVIENDA FAMILIAR, y no podrá darle otro uso, ni ceder o transferir el arrendamiento sin la autorización escrita del ARRENDADOR. El incumplimiento de esta cláusula dará derecho al ARRENDADOR para dar por terminado el contrato y exigir la entrega del inmueble o, en caso de cesión o subarriendo, celebrar un nuevo contrato con los usuarios reales, sin necesidad de requerimientos Judiciales o privados, a los cuales renuncia EL ARRENDATARIO. Parágrafo primero: EL ARRENDATARIO no destinará el inmueble a fines ilícitos, y en consecuencia se obliga a no utilizarlo para ocultar o depositar armas, explosivos o dineros de grupos terroristas o artículos de contrabando o para que en él se elaboren, almacenen o vendan drogas estupefacientes o sustancias alucinógenas y afines. EL ARRENDATARIO se obliga a no guardar o permitir que se guarden en el inmueble arrendado sustancias inflamables o explosivas que pongan en peligro la seguridad del mismo.'],
            ['numero'=>'TERCERA',         'titulo'=>'Pago, oportunidad y sitio', 'orden'=>3,  'contenido'=>'EL ARRENDATARIO se obliga a pagar el valor acordado de forma anticipada, pagaderos dentro de los cinco (5) días de cada periodo mensual dentro de los plazos previstos, en la Oficina de Serviarrendar SAS., dirección carrera 13 No. 11 – 15, oficina 103 de Ocaña o a su orden, o en su defecto consignados en el Bancolombia con el recibo de pago correspondiente. Parágrafo primero: EL ARRENDATARIO asumirá los costos de comisiones y notas débitos que se le descuenten a EL ARRENDADOR por cancelar su canon de arrendamiento desde otras plazas diferentes a Ocaña (Norte de Santander), transferencias, entre otros. Parágrafo segundo: La mera tolerancia de EL ARRENDADOR en aceptar el pago del precio del arrendamiento con posterioridad al plazo previsto para tal fin, no será suficiente para modificar las previsiones que al respecto han acordado las partes.'],
            ['numero'=>'CUARTA',          'titulo'=>'Incremento en el precio',   'orden'=>4,  'contenido'=>'Vencido el primer año de vigencia de este contrato y así sucesivamente cada doce (12) mensualidades, en caso de prorroga tácita o expresa, en forma automática y sin necesidad de requerimiento alguno entre las partes, el precio mensual del arrendamiento se incrementará conforme al IPC para la VIVIENDA URBANA. Al suscribir este contrato el ARRENDATARIO y el deudor solidario quedan plenamente notificados de todos los reajustes automáticos pactados en este contrato y que han de operar durante la vigencia del mismo.'],
            ['numero'=>'QUINTA',          'titulo'=>'Mora',                       'orden'=>5,  'contenido'=>'La mora por falta de pago de la renta mensual en la oportunidad y la forma acordada facultará al ARRENDADOR para hacer cesar el arriendo y exigir judicial o extrajudicialmente la restitución del bien, y presentar el respectivo cobro ejecutivo en contra de él y su deudor solidario. Parágrafo primero: Si produce mora en el pago del precio del arrendamiento, EL ARRENDATARIO, además del canon o cánones debidos, reconocerá y pagará durante ella a EL ARRENDADOR el doble de los intereses moratorios calculados con la tasa máxima permitida para la mora en los créditos de libre consumo.'],
            ['numero'=>'SEXTA',           'titulo'=>'Servicios',                  'orden'=>6,  'contenido'=>'Están a cargo del ARRENDATARIO los servicios públicos de: {SERVICIOS} y los siguientes servicios adicionales: especiales de telefonía, larga distancia, internet, cuota de administración de propiedad horizontal o celaduría, con los incrementos que al respecto decrete la Asamblea de copropietarios, y pagados directamente por EL ARRENDATARIO sin que el ARRENDADOR tenga responsabilidad alguna.'],
            ['numero'=>'SÉPTIMA',         'titulo'=>'Cobro Extrajudicial',        'orden'=>7,  'contenido'=>'Si el incumplimiento de la obligación de cancelar oportunamente los cánones de arrendamiento, servicios públicos, cuotas de administración o cualquier otra erogación derivada del contrato, diere lugar a alguna diligencia de cobro extrajudicial, EL ARRENDATARIO se obliga a pagar, como sanción moratoria por concepto de Gestión de Cobro una suma equivalente al diez por ciento (10%) de la suma adeudada. (Art. 1629 C. C.)'],
            ['numero'=>'OCTAVA',          'titulo'=>'Recibo y Estado',            'orden'=>8,  'contenido'=>'EL ARRENDATARIO declara que ha recibido el inmueble objeto de este contrato en buen estado, conforme al inventario que se adjunta, el cual hace parte de este contrato. EL ARRENDATARIO a la terminación del contrato, deberá devolver al ARRENDADOR el inmueble en el mismo estado de funcionamiento, salvo el deterioro proveniente del uso legítimo.'],
            ['numero'=>'NOVENA',          'titulo'=>'Mejoras',                    'orden'=>9,  'contenido'=>'EL ARRENDATARIO tendrá a su cargo las reparaciones locativas a que se refiere la ley (C.C. Arts. 2028, 2029 y 2030) y no podrá realizar otras sin el consentimiento escrito del ARRENDADOR. EL ARRENDATARIO renuncia expresamente a descontar de la renta el valor de las reparaciones indispensables, a que se refiere el artículo 27 de la Ley 820 de 2003.'],
            ['numero'=>'DÉCIMA',          'titulo'=>'Reparaciones Necesarias',   'orden'=>10, 'contenido'=>'Las reparaciones necesarias o indispensables no locativas serán a cargo de EL ARRENDADOR. EL ARRENDATARIO deberá avisar a EL ARRENDADOR, de forma oportuna y mediante comunicación escrita, de la ocurrencia del daño que origina la necesidad de reparación.'],
            ['numero'=>'DÉCIMA PRIMERA',  'titulo'=>'Exención de responsabilidad','orden'=>11,'contenido'=>'EL ARRENDADOR no asume responsabilidad alguna por los daños o perjuicios que EL ARRENDATARIO pueda sufrir por caso fortuito, fuerza mayor o causas atribuibles a terceros, ni por hurtos, ni por siniestros causados por incendio, inundación o terrorismo.'],
            ['numero'=>'DÉCIMA SEGUNDA',  'titulo'=>'Deudor Solidario',           'orden'=>12, 'contenido'=>'{DEUDOR_SOLIDARIO}, me declaro deudor solidario del señor {ARRENDATARIO}, en forma solidaria e indivisible, en todas las cargas y obligaciones contenidas en el presente contrato, tanto y durante el término inicialmente pactado como durante sus prórrogas o renovaciones expresas o tácitas y hasta que se produzca la entrega material del inmueble al ARRENDADOR.'],
            ['numero'=>'DÉCIMA TERCERA',  'titulo'=>'Cesión de Contrato',         'orden'=>13, 'contenido'=>'El deudor solidario acepta expresamente desde ahora cualquier cesión que EL ARRENDADOR haga respecto del presente contrato y ratifica su voluntad de que la notificación se surta con el solo envío de la nota de cesión acompañada de copia simple del contrato, por servicio postal autorizado.'],
            ['numero'=>'DÉCIMA CUARTA',   'titulo'=>'Abandono del inmueble',      'orden'=>14, 'contenido'=>'Al suscribir este contrato el arrendatario faculta expresamente al ARRENDADOR para penetrar en el inmueble y recuperar su tenencia, con el solo requisito de la presencia de dos testigos, siempre que el mismo permanezca abandonado o deshabitado por el término de un mes.'],
            ['numero'=>'DÉCIMA QUINTA',   'titulo'=>'Obligaciones de las partes', 'orden'=>15, 'contenido'=>'Son obligaciones de las partes las siguientes: a) Del ARRENDADOR: 1. Entregar al ARRENDATARIO en la fecha convenida el inmueble en buen estado de servicio, seguridad y sanidad. 2. Mantener en el inmueble los servicios en buen estado. b) Del ARRENDATARIO: 1. Pagar al ARRENDADOR el precio del arrendamiento. 2. Cuidar el inmueble y las cosas recibidas en arrendamiento. 3. Cumplir con las normas del reglamento de propiedad horizontal.'],
            ['numero'=>'DÉCIMA SEXTA',    'titulo'=>'Terminación del contrato',   'orden'=>16, 'contenido'=>'Son causales de terminación del contrato en forma unilateral, por parte del ARRENDADOR las previstas por el artículo 16 de la ley 56 de 1985; y por parte del ARRENDATARIO los consagradas en el artículo 17 de la misma ley. Además: a) La cesión o subarriendo b) El cambio de destinación c) El no pago del precio dentro del término previsto d) La destinación del inmueble para fines ilícitos.'],
            ['numero'=>'DÉCIMA SÉPTIMA',  'titulo'=>'Cesión de los Derechos',     'orden'=>17, 'contenido'=>'Estipulan expresamente los contratantes que este contrato no formará parte integral de ningún establecimiento de comercio y que el ARRENDATARIO se obliga expresamente a no ceder, a no subarrendar el inmueble, ni transferir su tenencia.'],
            ['numero'=>'DÉCIMA OCTAVA',   'titulo'=>'Preaviso',                   'orden'=>18, 'contenido'=>'EL ARRENDADOR podrá dar por terminado el contrato mediante preaviso dado al ARRENDATARIO con Tres (3) meses de anticipación. Así mismo, EL ARRENDATARIO podrá dar por terminado unilateralmente el contrato previo aviso escrito al ARRENDADOR, con un plazo no menor de tres (3) meses y el pago de una indemnización equivalente al precio de tres (3) meses de arrendamiento.'],
            ['numero'=>'DÉCIMA NOVENA',   'titulo'=>'Sanción por retardo en la restitución','orden'=>19,'contenido'=>'Si vencido el presente contrato y producido el desahucio, la parte ARRENDATARIO no hiciere devolución de la tenencia del inmueble, pagará a título de pena TRES (3) cánones adicionales por cada día de mora en la entrega.'],
            ['numero'=>'VIGÉSIMA',        'titulo'=>'Cláusula penal',             'orden'=>20, 'contenido'=>'El incumplimiento por cualquiera de las partes de las obligaciones derivadas de este contrato la constituirá en deudor del ARRENDADOR por la suma equivalente al triple del precio mensual del arrendamiento que esté vigente en el momento en que tal incumplimiento se presente.'],
            ['numero'=>'VIGÉSIMA PRIMERA','titulo'=>'Solidaridad',                'orden'=>21, 'contenido'=>'Los derechos y las obligaciones derivadas del presente contrato de arrendamiento son solidarias, tanto entre ARRENDADORES como entre ARRENDATARIOS y DEUDORES SOLIDARIOS.'],
            ['numero'=>'VIGÉSIMA SEGUNDA','titulo'=>'Gastos',                     'orden'=>22, 'contenido'=>'Los gastos que cause este instrumento serán a cargo de EL ARRENDATARIO y sus DEUDORES SOLIDARIOS.'],
            ['numero'=>'VIGÉSIMA TERCERA','titulo'=>'Requerimientos',             'orden'=>23, 'contenido'=>'EL ARRENDATARIO y los DEUDORES SOLIDARIOS renuncian expresamente a los requerimientos previstos en la ley, especialmente a los contenidos en los artículos 1594 y 2007 del Código Civil relativos a la constitución en mora.'],
            ['numero'=>'VIGÉSIMA CUARTA', 'titulo'=>'Autorización',               'orden'=>24, 'contenido'=>'EL ARRENDATARIO y sus deudores solidarios autorizan expresamente al ARRENDADOR para incorporar, reportar, procesar y consultar en bancos de datos la información relacionada o derivada de este contrato.'],
            ['numero'=>'VIGÉSIMA QUINTA', 'titulo'=>'Copia del Contrato',         'orden'=>25, 'contenido'=>'EL ARRENDATARIO manifiesta que ha recibido copia del presente contrato a satisfacción, con las firmas originales a la firma del presente documento. Parágrafo primero: Autorizo a LA INMOBILIARIA SERVIARRENDAR SAS para la recolección, almacenamiento y uso de mis datos personales con la finalidad de vincularme como cliente.'],
            ['numero'=>'VIGÉSIMA SEXTA',  'titulo'=>'Datos de Contacto',          'orden'=>26, 'contenido'=>'Para efectos judiciales y extrajudiciales las partes se notificarán en las siguientes direcciones. Arrendador: YANETH DEL CARMEN PEREZ AREVALO a la dirección: carrera 13 # 11-15 ofc 103 centro- Ocaña o al correo electrónico serviarrendarltda@gmail.com, número de celular 3186934710. Arrendatario: {DIRECCION_ARRENDATARIO}.'],
        ];

        foreach ($clausulasVivienda as $c) {
            ContractClause::create([
                'contract_template_id' => $vivienda->id,
                'numero'       => $c['numero'],
                'titulo'       => $c['titulo'],
                'tipo'         => 'clausula',
                'contenido'    => $c['contenido'],
                'orden'        => $c['orden'],
                'es_editable'  => true,
                'es_obligatoria' => true,
                'is_active'    => true,
            ]);
        }

        // ── COMERCIAL ────────────────────────────────────────
        $comercial = ContractTemplate::create([
            'nombre'        => 'Contrato de Arrendamiento Comercial — Serviarrendar S.A.S',
            'tipo_contrato' => 'arrendamiento_comercial',
            'is_default'    => true,
            'is_active'     => true,
        ]);

        $clausulasComercial = [
            ['numero'=>'PRIMERA',          'titulo'=>'Objeto del contrato',        'orden'=>1,  'contenido'=>'Mediante el presente contrato el ARRENDADOR concede al ARRENDATARIO el goce del inmueble que adelante se identifica por su dirección, de acuerdo con el inventario que las partes firman por separado.'],
            ['numero'=>'SEGUNDA',          'titulo'=>'Destinación',                'orden'=>2,  'contenido'=>'EL ARRENDATARIO se obliga a usar el inmueble para {DESTINACION}, su actividad comercial será {ACTIVIDAD_COMERCIAL} y no podrá darle otro uso, ni ceder o transferir el arrendamiento sin la autorización escrita del ARRENDADOR.'],
            ['numero'=>'TERCERA',          'titulo'=>'Pago, oportunidad y sitio',  'orden'=>3,  'contenido'=>'EL ARRENDATARIO se obliga a pagar el valor acordado de forma anticipada, pagaderos dentro de los cinco (5) días de cada periodo mensual dentro de los plazos previstos, en la Oficina de Serviarrendar SAS, dirección carrera 13 No. 11 – 15, oficina 103 de Ocaña o a su orden, o en su defecto consignados en el Bancolombia o Banco de Bogotá con el recibo de pago correspondiente.'],
            ['numero'=>'CUARTA',           'titulo'=>'Incremento en el precio',    'orden'=>4,  'contenido'=>'Vencido el primer año de vigencia de este contrato y así sucesivamente cada doce (12) mensualidades, en caso de prórroga tácita o expresa, en forma automática y sin necesidad de requerimiento alguno entre las partes, el precio mensual del arrendamiento se incrementará en (10%). Al suscribir este contrato el ARRENDATARIO y el deudor solidario quedan plenamente notificados de todos los reajustes automáticos pactados en este contrato.'],
            ['numero'=>'QUINTA',           'titulo'=>'Mora',                        'orden'=>5,  'contenido'=>'La mora por falta de pago de la renta mensual en la oportunidad y forma acordada facultará al ARRENDADOR para hacer cesar el arriendo y exigir judicial o extrajudicialmente la restitución del bien, y presentar el respectivo cobro ejecutivo en contra de él.'],
            ['numero'=>'SEXTA',            'titulo'=>'Servicios',                   'orden'=>6,  'contenido'=>'Están a cargo del ARRENDATARIO los servicios públicos de: {SERVICIOS}, y los siguientes servicios adicionales: telefonía, internet, cuota de administración de propiedad horizontal o celaduría, con los incrementos que al respecto decrete la Asamblea de copropietarios.'],
            ['numero'=>'SÉPTIMA',          'titulo'=>'Cobro Extrajudicial',         'orden'=>7,  'contenido'=>'Si el incumplimiento de la obligación de cancelar oportunamente los cánones de arrendamiento, servicios públicos, cuotas de administración o cualquier otra erogación derivada del contrato, diere lugar a alguna diligencia de cobro extrajudicial, EL ARRENDATARIO se obliga a pagar como sanción moratoria una suma equivalente al diez por ciento (10%) de la suma adeudada.'],
            ['numero'=>'OCTAVA',           'titulo'=>'Recibo y Estado',             'orden'=>8,  'contenido'=>'EL ARRENDATARIO declara que ha recibido el inmueble en buen estado, conforme al inventario que se adjunta. EL ARRENDATARIO a la terminación del contrato deberá devolver el inmueble en el mismo estado, salvo el deterioro proveniente del uso legítimo.'],
            ['numero'=>'NOVENA',           'titulo'=>'Mejoras',                     'orden'=>9,  'contenido'=>'EL ARRENDATARIO tendrá a su cargo las reparaciones locativas y no podrá realizar otras sin el consentimiento escrito del ARRENDADOR. EL ARRENDATARIO renuncia expresamente a descontar de la renta el valor de las reparaciones indispensables.'],
            ['numero'=>'DÉCIMA',           'titulo'=>'Autorización de Mejoras',     'orden'=>10, 'contenido'=>'EL ARRENDADOR autoriza de forma expresa al ARRENDATARIO para realizar las mejoras correspondientes, estas adecuaciones serán asumidas al 100% por el ARRENDATARIO. Las mejoras quedarán en el inmueble y el arrendatario no podrá solicitar ningún derecho de reembolso.', 'es_editable'=>true],
            ['numero'=>'DÉCIMA PRIMERA',   'titulo'=>'Reparaciones Necesarias',    'orden'=>11, 'contenido'=>'Las reparaciones necesarias o indispensables no locativas serán a cargo de EL ARRENDADOR. EL ARRENDATARIO deberá avisar a EL ARRENDADOR, de forma oportuna y mediante comunicación escrita, de la ocurrencia del daño que origina la necesidad de reparación.'],
            ['numero'=>'DÉCIMA SEGUNDA',   'titulo'=>'Deudor Solidario',            'orden'=>12, 'contenido'=>'{DEUDORES_SOLIDARIOS} nos declaramos deudores solidarios del señor {ARRENDATARIO}, en forma solidaria e indivisible, en todas las cargas y obligaciones contenidas en el presente contrato.'],
            ['numero'=>'DÉCIMA TERCERA',   'titulo'=>'Cesión de Contrato',          'orden'=>13, 'contenido'=>'Los deudores solidarios aceptan expresamente desde ahora cualquier cesión que EL ARRENDADOR haga respecto del presente contrato.'],
            ['numero'=>'DÉCIMA CUARTA',    'titulo'=>'Abandono del inmueble',       'orden'=>14, 'contenido'=>'Al suscribir este contrato el arrendatario faculta expresamente al ARRENDADOR para penetrar en el inmueble y recuperar su tenencia, con el solo requisito de la presencia de dos testigos, siempre que el mismo permanezca abandonado por el término de un mes.'],
            ['numero'=>'DÉCIMA QUINTA',    'titulo'=>'Obligaciones de las partes',  'orden'=>15, 'contenido'=>'Son obligaciones de las partes: a) Del ARRENDADOR: 1. Entregar el inmueble en buen estado. 2. Mantener los servicios en buen estado. b) Del ARRENDATARIO: 1. Pagar el canon de arrendamiento. 2. Cuidar el inmueble. 3. Cumplir con las normas del reglamento de propiedad horizontal.'],
            ['numero'=>'DÉCIMA SEXTA',     'titulo'=>'Terminación del contrato',    'orden'=>16, 'contenido'=>'Son causales de terminación: a) La cesión o subarriendo b) El cambio de destinación c) El no pago del precio d) La destinación del inmueble para fines ilícitos e) La realización de mejoras sin autorización f) La no cancelación oportuna de servicios públicos.'],
            ['numero'=>'DÉCIMA SÉPTIMA',   'titulo'=>'Cesión de los Derechos',      'orden'=>17, 'contenido'=>'El ARRENDATARIO se obliga expresamente a no ceder, a no subarrendar el inmueble, ni transferir su tenencia. En caso de que EL ARRENDADOR autorice la cesión, el ARRENDATARIO acepta cancelar el 20% del canon de arrendamiento por la gestión llevada a cabo.'],
            ['numero'=>'DÉCIMA OCTAVA',    'titulo'=>'Preaviso',                    'orden'=>18, 'contenido'=>'EL ARRENDADOR podrá dar por terminado el contrato mediante preaviso con seis (6) meses de anticipación. EL ARRENDATARIO podrá dar por terminado unilateralmente el contrato con un plazo no menor de seis (6) meses y el pago de una indemnización equivalente a seis (6) meses de arrendamiento.'],
            ['numero'=>'DÉCIMA NOVENA',    'titulo'=>'Sanción por retardo',         'orden'=>19, 'contenido'=>'Si vencido el presente contrato el ARRENDATARIO no hiciere devolución del inmueble, pagará a título de pena TRES (3) cánones adicionales por cada día de mora en la entrega.'],
            ['numero'=>'VIGÉSIMA',         'titulo'=>'Cláusula penal',              'orden'=>20, 'contenido'=>'El incumplimiento por cualquiera de las partes constituirá en deudor del ARRENDATARIO por la suma equivalente al triple del precio mensual del arrendamiento vigente.'],
            ['numero'=>'VIGÉSIMA PRIMERA', 'titulo'=>'Solidaridad',                 'orden'=>21, 'contenido'=>'Los derechos y las obligaciones derivadas del presente contrato son solidarias, tanto entre ARRENDADORES como entre ARRENDATARIOS y DEUDORES SOLIDARIOS.'],
            ['numero'=>'VIGÉSIMA SEGUNDA', 'titulo'=>'Requerimientos',              'orden'=>22, 'contenido'=>'EL ARRENDATARIO y los DEUDORES SOLIDARIOS renuncian expresamente a los requerimientos previstos en la ley, especialmente a los artículos 1594 y 2007 del Código Civil.'],
            ['numero'=>'VIGÉSIMA TERCERA', 'titulo'=>'Autorización',                'orden'=>23, 'contenido'=>'EL ARRENDATARIO y sus deudores solidarios autorizan expresamente al ARRENDADOR para incorporar, reportar, procesar y consultar en bancos de datos la información relacionada con este contrato.'],
            ['numero'=>'VIGÉSIMA CUARTA',  'titulo'=>'No existe Good Will',         'orden'=>24, 'contenido'=>'Las partes renuncian expresamente a exigir suma alguna por concepto de prima comercial o GOOD WILL, o crédito comercial creado como valor a la terminación del presente contrato.'],
            ['numero'=>'VIGÉSIMA QUINTA',  'titulo'=>'Copia del Contrato',          'orden'=>25, 'contenido'=>'EL ARRENDATARIO manifiesta que ha recibido copia del presente contrato a satisfacción, con las firmas originales.'],
            ['numero'=>'VIGÉSIMA SEXTA',   'titulo'=>'Gastos',                      'orden'=>26, 'contenido'=>'Los gastos que cause este instrumento serán a cargo de EL ARRENDATARIO y sus DEUDORES SOLIDARIOS.'],
            ['numero'=>'VIGÉSIMA SÉPTIMA', 'titulo'=>'Datos de Contacto',           'orden'=>27, 'contenido'=>'Para efectos judiciales y extrajudiciales las partes se notificarán: Arrendador: YANETH DEL CARMEN PEREZ AREVALO, carrera 13 # 11-15 ofc 103 centro-Ocaña, serviarrendarltda@gmail.com, cel. 3186934710. Arrendatario: {DIRECCION_ARRENDATARIO}. Deudores solidarios: {DIRECCION_DEUDORES}.'],
            ['numero'=>'VIGÉSIMA OCTAVA',  'titulo'=>'Autorización de datos',       'orden'=>28, 'contenido'=>'Autorizo a LA INMOBILIARIA SERVIARRENDAR SAS para la recolección, almacenamiento y uso de mis datos personales con la finalidad de vincularme como cliente, autorizo el tratamiento de mis datos para los fines necesarios para la prestación de los servicios encargados.'],
        ];

        foreach ($clausulasComercial as $c) {
            ContractClause::create([
                'contract_template_id' => $comercial->id,
                'numero'        => $c['numero'],
                'titulo'        => $c['titulo'],
                'tipo'          => 'clausula',
                'contenido'     => $c['contenido'],
                'orden'         => $c['orden'],
                'es_editable'   => $c['es_editable'] ?? true,
                'es_obligatoria'=> true,
                'is_active'     => true,
            ]);
        }

        $this->command->info('✅ Plantillas de arrendamiento vivienda y comercial creadas — ' . $vivienda->clauses()->count() . ' + ' . $comercial->clauses()->count() . ' cláusulas');
    }
}
