<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // ══════════════════════════════════════════════════════════
        // TEMPLATE 2 — VIVIENDA URBANA
        // ══════════════════════════════════════════════════════════

        // SEGUNDA — Destinación (párrafo completo con enfermedades infectocontagiosas)
        DB::table('contract_clauses')->where('id', 27)->update(['contenido' =>
            'EL ARRENDATARIO se obliga a usar el inmueble para la VIVIENDA FAMILIAR, y no podrá darle otro uso, ni ceder o transferir el arrendamiento sin la autorización escrita del ARRENDADOR. El incumplimiento de esta cláusula dará derecho al ARRENDADOR para dar por terminado el contrato y exigir la entrega del inmueble o, en caso de cesión o subarriendo, celebrar un nuevo contrato con los usuarios reales, sin necesidad de requerimientos Judiciales o privados, a los cuales renuncia EL ARRENDATARIO. Parágrafo primero: EL ARRENDATARIO no destinará el inmueble a fines ilícitos, y en consecuencia se obliga a no utilizarlo para ocultar o depositar armas, explosivos o dineros de grupos terroristas o artículos de contrabando o para que en él se elaboren, almacenen o vendan drogas estupefacientes o sustancias alucinógenas y afines. EL ARRENDATARIO se obliga a no guardar o permitir que se guarden en el inmueble arrendado sustancias inflamables o explosivas que pongan en peligro la seguridad del mismo, y en caso que ocurriera dentro del inmueble enfermedad infectocontagiosa, serán del ARRENDATARIO los gastos de desafección que ordenen las autoridades sanitarias.'
        ]);

        // TERCERA — Pago (agregar párrafo segundo completo)
        DB::table('contract_clauses')->where('id', 28)->update(['contenido' =>
            'EL ARRENDATARIO se obliga a pagar el valor acordado de forma anticipada, pagaderos dentro de los cinco (5) días de cada periodo mensual dentro de los plazos previstos, en la Oficina de Serviarrendar SAS., dirección carrera 13 No. 11 – 15, oficina 103 de Ocaña o a su orden, o en su defecto consignados en el Bancolombia con el recibo de pago correspondiente. Parágrafo primero: EL ARRENDATARIO asumirá los costos de comisiones y notas débitos que se le descuenten a EL ARRENDADOR por cancelar su canon de arrendamiento desde otras plazas diferentes a Ocaña (Norte de Santander), transferencias, entre otros. Parágrafo segundo: La mera tolerancia de EL ARRENDADOR en aceptar el pago del precio del arrendamiento con posterioridad al plazo previsto para tal fin, no será suficiente para modificar las previsiones que al respecto han acordado las partes. Tampoco se consideran variadas las estipulaciones relativas al precio del arrendamiento por la recepción de pagos parciales. De conformidad con lo anterior, la aceptación de pagos parciales no invalidará los efectos que la mora produzca a cargo de EL ARRENDATARIO.'
        ]);

        // QUINTA — Mora (agregar párrafo de cobro extrajudicial)
        DB::table('contract_clauses')->where('id', 30)->update(['contenido' =>
            'La mora por falta de pago de la renta mensual en la oportunidad y la forma acordada facultará al ARRENDADOR para hacer cesar el arriendo y exigir judicial o extrajudicialmente la restitución del bien, y presentar el respectivo cobro ejecutivo en contra de él y su deudor solidario. Parágrafo primero: Si produce mora en el pago del precio del arrendamiento, EL ARRENDATARIO, además del canon o cánones debidos, reconocerá y pagará durante ella a EL ARRENDADOR el doble de los intereses moratorios calculados con la tasa máxima permitida para la mora en los créditos de libre consumo. Se hiciere en cheque y este resultare impagado EL ARRENDATARIO pagará, además, la sanción del veinte por ciento (20%) del valor del cheque, de conformidad con lo dispuesto en el artículo 731 del código de comercio. Todo lo anterior sin perjuicio de que EL ARRENDADOR pueda iniciar las acciones que, por incumplimiento, correspondan. Parágrafo segundo: Si el incumplimiento de la obligación de cancelar oportunamente los cánones de arrendamiento, servicios públicos, cuotas de administración o cualquier otra erogación derivada del contrato, diere lugar a alguna diligencia de cobro extrajudicial, EL ARRENDATARIO se obliga a pagar, como sanción moratoria por concepto de Gestión de Cobro una suma equivalente al diez por ciento (10%) de la suma adeudada. (Art. 1629 C. C.) — Dicha suma podrá ser exigida por la vía ejecutiva, sin perjuicio de las demás sanciones que por el incumplimiento o por mora se han pactado en este contrato y sin necesidad de requerimiento alguno.'
        ]);

        // SEXTA — Servicios (agregar párrafos completos + Línea Telefónica)
        DB::table('contract_clauses')->where('id', 31)->update(['contenido' =>
            'Están a cargo del ARRENDATARIO los servicios públicos de: {SERVICIOS} y los siguientes servicios adicionales: especiales de telefonía, larga distancia, publicaciones en el directorio telefónico, internet, cuota de sostenimiento de T.V. Cable, cuota de sostenimiento de antena parabólica, cuota de administración de propiedad horizontal o celaduría, con los incrementos que al respecto decrete la Asamblea de copropietarios, y pagados directamente por EL ARRENDATARIO sin que el ARRENDADOR tenga responsabilidad alguna por la correcta o deficiente prestación de tales servicios. Parágrafo primero: EL ARRENDATARIO se obliga a pagar las sanciones, costos y multas que las Empresas de Acueducto, Energía Eléctrica, Teléfono, Gas o cualquier otra Autoridad, Empresa, Juntas Comunales y Juntas Administradoras de los condominios del Régimen de Propiedad Horizontal impongan, durante la vigencia del presente contrato por las infracciones de los respectivos reglamentos o por no haber pagado oportunamente tales servicios e indemnizará AL ARRENDADOR por los perjuicios que pudieran tener por tales infracciones u omisiones. Es entendido que EL ARRENDADOR puede, si lo considera conveniente, hacer las respectivas cancelaciones para obtener la normalización de los mencionados servicios, así como también podrá pagar las sanciones, impuestos y multas, y en estos casos su costo deberá ser reembolsado en forma inmediata por EL ARRENDATARIO, pudiendo ser cobrado por la vía ejecutiva, sin necesidad de requerimiento alguno, con la simple presentación de los respectivos recibos, debidamente cancelados. Parágrafo segundo: Línea Telefónica. Se deja expresa constancia que el inmueble se arrienda SIN LÍNEA TELEFÓNICA. Si durante la vigencia de este contrato se instalare en el inmueble arrendado una o más líneas telefónicas EL ARRENDATARIO junto con sus DEUDORES SOLIDARIOS se comprometen al pago del servicio telefónico correspondiente y a retirar a la terminación del Contrato de Arrendamiento las líneas adicionales que se le hayan autorizado posteriormente a la firma del presente contrato.'
        ]);

        // SÉPTIMA — Cobro Extrajudicial (agregar párrafo ASEGURADORA)
        DB::table('contract_clauses')->where('id', 32)->update(['contenido' =>
            'Si el incumplimiento de la obligación de cancelar oportunamente los cánones de arrendamiento, cuotas de administración, servicios públicos, celaduría y/o vigilancia así como cualquier otra erogación derivada del presente contrato, diere lugar a alguna diligencia de cobro extrajudicial, EL ARRENDATARIO y sus DEUDORES SOLIDARIOS se obligan a pagar a la entidad encargada de tal gestión los costos que ello genere (Gestión de cobro, intereses, carta de recordatorio de canon y honorarios), ello en razón a que los gastos que ocasione la obtención del pago son de cuenta de los deudores; lo anterior sin perjuicio de lo estipulado por la casa de cobranza, gestor jurídico, entidad aseguradora o afianzadora en sus manuales de cobranza, y aquello que el juez ordenare acerca de las costas judiciales, conforme disposición expresa del artículo 1629 del Código Civil. Parágrafo: El ARRENDATARIO y los DEUDOR(ES) SOLIDARIO(S) manifiestan conocer y aceptar desde ahora, la póliza de seguro de arrendamiento expedida por la compañía ASEGURADORA elegida por el ARRENDADOR, así como las sumas de dinero que eventualmente se llegaran a causar como indemnización a favor de el arrendador con ocasión del incumplimiento de las obligaciones pactadas en el presente contrato de arrendamiento. En el evento en que la ASEGURADORA indemnice el incumplimiento de las obligaciones dinerarias derivadas del presente contrato, EL ARRENDATARIO y los DEUDOR(ES) SOLIDARIO(S) se obligan a: (1) Pagar y reconocer a favor de la compañía ASEGURADORA las sumas que este último llegue a pagar a favor de EL ARRENDADOR como resultado del incumplimiento, entendiendo que ha operado una subrogación legal de todos los derechos, acciones y privilegios, en los términos de los artículos 1036 y s.s. del Código de Comercio, art. 1096 de la misma fuente normativa, arts. 1666 a 1671 del Código Civil y demás normas concordantes. (2) Pagar y reconocer honorarios de cobranza, en etapa judicial y extrajudicial de las sumas adeudadas, así como las ocasionadas por el proceso de restitución del inmueble que se adelante en contra de EL ARRENDATARIO.'
        ]);

        // OCTAVA — Recibo y Estado (agregar cláusula de pintura y 15%)
        DB::table('contract_clauses')->where('id', 33)->update(['contenido' =>
            'EL ARRENDATARIO declara que ha recibido el inmueble objeto de este contrato en buen estado, conforme al inventario que se adjunta, el cual hace parte de este contrato, y en el mismo se determinan los servicios, cosas y usos conexos y adicionales. EL ARRENDATARIO a la terminación del contrato, deberá devolver al ARRENDADOR el inmueble en el mismo estado de funcionamiento, todo lo cual consta en el referido anexo, salvo el deterioro proveniente legítimo, y/o EL ARRENDATARIO hará cancelación de los daños ocasionados. EL ARRENDATARIO se obliga a conservarlo y restituirlo en las mismas condiciones, especialmente en lo referente a la pintura general del inmueble. Por medio de la firma de este contrato se compromete a entregarlo nuevamente pintado o en su defecto autoriza para que EL ARRENDADOR efectúe dicha obra asumiendo EL ARRENDATARIO los costos de la misma. Para este efecto convienen las partes que las facturas de reparación de daños, de obra de pintura o de reposición de faltantes junto con el contrato de arrendamiento prestan mérito ejecutivo suficiente y adicionalmente EL ARRENDATARIO cancelará el 15% adicionalmente a EL ARRENDADOR sobre el valor de la obra ejecutada, a la terminación del arrendamiento, o cuando este haya de cesar por alguna de las causales previstas, salvo el deterioro proveniente del tiempo y del uso legítimo.'
        ]);

        // NOVENA — Mejoras (agregar Párrafos Primero y Segundo completos)
        DB::table('contract_clauses')->where('id', 34)->update(['contenido' =>
            'EL ARRENDATARIO tendrá a su cargo las reparaciones locativas a que se refiere la ley (C.C. Arts. 2028, 2029 y 2030) y no podrá realizar otras sin el consentimiento escrito del ARRENDADOR. En todo caso, EL ARRENDATARIO podrá retirar las mejoras y/o reformas introducidas en el inmueble, siempre y cuando se pueda proceder a ello sin detrimento del inmueble; en caso contrario, las mejoras quedarán de propiedad de EL ARRENDADOR, quien no estará obligado a reconocer, por tal concepto, suma alguna a favor de EL ARRENDATARIO si se ejecutaren accederán al propietario del inmueble sin indemnización para quien las efectuó. EL ARRENDATARIO renuncia expresamente a descontar de la renta el valor de las reparaciones indispensables, a que se refiere el artículo 27 de la Ley 820 de 2003. Parágrafo Primero: Si EL ARRENDATARIO por alguna circunstancia efectuara mejoras en el inmueble objeto de este contrato de arrendamiento, no obstante la prohibición contenida en esta cláusula y tales mejoras a juicio del ARRENDADOR constituyeran una depreciación para el inmueble, EL ARRENDATARIO se obliga a retirarlas y a entregar el bien en el estado en lo recibió. Si no diere cumplimiento a dicha obligación, la depreciación del inmueble será estimada parcialmente y su valor será exigible por la vía ejecutiva. Parágrafo segundo: Mejoras Locativas. Las reparaciones locativas serán de cargo de EL ARRENDATARIO, quien deberá proceder a ellas de inmediato y sin necesidad de que medie autorización de EL ARRENDADOR. Se entiende por reparaciones locativas aquellas que deben hacerse para arreglar los deterioros que ordinariamente se producen por culpa de EL ARRENDATARIO o de sus dependientes, como, por ejemplo, descalabros de paredes, rotura de cristales, etc.'
        ]);

        // DÉCIMA — Reparaciones Necesarias (contenido completo)
        DB::table('contract_clauses')->where('id', 35)->update(['contenido' =>
            'Las reparaciones necesarias o indispensables no locativas serán a cargo de EL ARRENDADOR. EL ARRENDATARIO deberá avisar a EL ARRENDADOR, de forma oportuna y mediante comunicación escrita, de la ocurrencia del daño que origina la necesidad de reparación. En dicha comunicación EL ARRENDATARIO deberá indicar la naturaleza del daño y su gravedad. En caso de especial urgencia el aviso podrá darse inicialmente de manera verbal, telefónica o vía celular, comprometiéndose a que el día siguiente se reitere por escrito. Una vez conocida la ocurrencia del daño y dentro de un término prudencial, EL ARRENDADOR deberá adelantar la correspondiente reparación. No serán de cargo de EL ARRENDADOR aquellas reparaciones que se hayan hecho necesarias por culpa de EL ARRENDATARIO, de sus dependientes, huéspedes o familiares. Se entiende por reparaciones necesarias aquellas indispensables para que la cosa pueda prestar su uso ordinario, así como aquellas sin las cuales la cosa podría perecer.'
        ]);

        // DÉCIMA PRIMERA — Exención de responsabilidad (agregar responsabilidad del inquilino)
        DB::table('contract_clauses')->where('id', 36)->update(['contenido' =>
            'EL ARRENDADOR no asume responsabilidad alguna por los daños o perjuicios que EL ARRENDATARIO pueda sufrir por caso fortuito, fuerza mayor o causas atribuibles a terceros, ni por hurtos, ni por siniestros causados por incendio, inundación o terrorismo. EL ARRENDATARIO asume la responsabilidad por los daños que puedan causar al inmueble o a los enseres y dotaciones de los vecinos o terceros, cuando estos provengan del descuido o negligencia de EL ARRENDATARIO, de sus dependientes, familia, huéspedes o subarrendatarios.'
        ]);

        // DÉCIMA SEGUNDA — Deudor Solidario (texto completo con variables)
        DB::table('contract_clauses')->where('id', 37)->update(['contenido' =>
            '{DEUDOR_SOLIDARIO}, me declaro deudor solidario de {ARRENDATARIO}, en forma solidaria e indivisible, en todas las cargas y obligaciones contenidas en el presente contrato, tanto y durante el término inicialmente pactado como durante sus prórrogas o renovaciones expresas o tácitas y hasta que se produzca la entrega material del inmueble al ARRENDADOR, por concepto de arrendamiento, servicios públicos indemnizaciones, daños en el inmueble, cuotas de administración, intereses moratorios, honorarios causados en caso de mora en el pago del arriendo por las gestiones de cobranza extrajudicial o judicial y las costas procesales a que sea condenado EL ARRENDATARIO en la cuantía señalada por el respectivo juzgado en el caso del proceso de restitución, cláusulas penales etc., las cuales podrán ser exigidas por EL ARRENDADOR a cualquiera de las obligaciones por la vía ejecutiva, sin necesidad de requerimientos privados o judiciales a los cuales renunciamos expresamente, sin que por razón de esta solidaridad asumamos el carácter de fiadores ni arrendatarios. Para este exclusivo efecto EL ARRENDATARIO otorga poder amplio y suficiente a los DEUDORES SOLIDARIOS en este mismo acto y al suscribirse el presente contrato.'
        ]);

        // DÉCIMA TERCERA — Cesión de Contrato (texto completo)
        DB::table('contract_clauses')->where('id', 38)->update(['contenido' =>
            '{DEUDORES_SOLIDARIOS}, como deudor(es) solidario(s) acepto(amos) expresamente desde ahora cualquier cesión que EL ARRENDADOR haga respecto del presente contrato y ratificamos nuestra voluntad de que la notificación de que trata el artículo 1960 del Código Civil se surta con el solo envío de la nota de cesión acompañada de copia simple del contrato, por servicio postal autorizado, a la dirección que aparece registrada en este contrato al pie de nuestras respectivas firmas.'
        ]);

        // DÉCIMA QUINTA — Obligaciones (agregar referencias Ley 56/85)
        DB::table('contract_clauses')->where('id', 40)->update(['contenido' =>
            'Son obligaciones de las partes las siguientes: a) Del ARRENDADOR: 1. Entregar al ARRENDATARIO en la fecha convenida el inmueble dado en arrendamiento en buen estado de servicio, seguridad y sanidad y poner a su disposición los servicios, cosas o usos conexos y los adicionales aquí convenidos. 2. Mantener en el inmueble los servicios, las cosas y los usos conexos y adicionales en buen estado de servir para el fin convenido en el contrato. 3. Entregar al ARRENDATARIO una copia del reglamento interno de propiedad horizontal al que se encuentra sometido el inmueble (ello cuando el inmueble arrendado esté sometido a dicho régimen). 4. Las demás obligaciones consagradas para los arrendadores en el capítulo II, Título XXVI, Libro 4 del Código Civil (Ley 56/85, art. 11). b) Del ARRENDATARIO: 1. Pagar al ARRENDADOR en el lugar convenido en la cláusula tercera del presente contrato, el precio del arrendamiento. En el evento que EL ARRENDADOR rehúse recibir en las condiciones y lugar aquí acordados, EL ARRENDATARIO podrá efectuarlo mediante consignación a favor del ARRENDADOR en las instituciones autorizados por el Gobierno Nacional para tal efecto de acuerdo con el procedimiento legal vigente. 2. Cuidar el inmueble y las cosas recibidas en arrendamiento. En caso de daños o deterioros distintos derivados del uso normal o de la acción del tiempo y que fueren imputables al mal uso del inmueble a su propia culpa, efectuar oportunamente y por su cuenta las reparaciones o sustituciones necesarias. 3. Cumplir con las normas consagradas en el reglamento de propiedad horizontal al que se encuentra sometido el inmueble arrendado (ello cuando el mismo esté sometido a dicho régimen), así como las demás disposiciones que dicte el Gobierno Nacional dirigidas a la protección de los derechos de todos los vecinos. 4. Las demás obligaciones consagradas para el arrendatario en el capítulo III, Título XXVI, Libro 4 del Código Civil (Ley 56/85, Art. 12).'
        ]);

        // DÉCIMA SEXTA — Terminación (ampliar causales)
        DB::table('contract_clauses')->where('id', 41)->update(['contenido' =>
            'Son causales de terminación del contrato en forma unilateral, por parte del ARRENDADOR las previstas por el artículo 16 de la ley 56 de 1985; y por parte del ARRENDATARIO los consagradas en el artículo 17 de la misma ley. Además, se da por terminado este contrato también si se realiza: a) La cesión o subarriendo b) El cambio de destinación del inmueble c) El no pago del precio dentro del término previsto en este contrato d) La destinación del inmueble para fines ilícitos o contrario a las buenas costumbres, o que representen peligro para el inmueble o la salubridad de sus habitantes e) La realización de mejoras, cambios o ampliaciones del inmueble, sin expresa autorización del ARRENDADOR f) La no cancelación oportuna de los servicios públicos a cargo del ARRENDATARIO g) La no cancelación del valor de las cuotas de administración, dentro de los términos pactados h) Cuando el ARRENDATARIO viole las normas del respectivo reglamento interno o de propiedad horizontal, o no pague las expensas comunes cuando el pago esté a su cargo i) Cuando el propietario o poseedor necesite el inmueble para ocuparlo, o cuando el inmueble haya de demolerse para efectuar una nueva construcción, o cuando se requiera desocuparlo con el fin de ejecutar obras indispensables para su reparación j) Cuando el inmueble haya de entregarse en cumplimiento de las obligaciones originadas en un contrato de compraventa k) Y demás previstas en la Ley.'
        ]);

        // DÉCIMA OCTAVA — Preaviso (agregar cita Ley 56/85)
        DB::table('contract_clauses')->where('id', 43)->update(['contenido' =>
            'EL ARRENDADOR podrá dar por terminado el contrato de arrendamiento durante cualquiera de sus prórrogas, mediante preaviso dado al ARRENDATARIO con Tres (3) meses de anticipación. Así mismo, EL ARRENDATARIO podrá dar por terminado unilateralmente el contrato de arrendamiento dentro del término inicial o el de sus prórrogas previo aviso escrito al ARRENDADOR, con un plazo no menor de tres (3) meses y el pago de una indemnización equivalente al precio de tres (3) meses de arrendamiento. Cumplidas estas condiciones EL ARRENDADOR estará obligado a recibir el inmueble; si no lo hiciere, EL ARRENDATARIO podrá hacer entrega provisional mediante la intervención de la autoridad administrativa competente, sin perjuicio de acudir a la acción judicial correspondiente. Parágrafo primero: No habrá lugar a la indemnización si el aviso de terminación por parte del ARRENDATARIO se refiere al término estipulado en este contrato (Ley 56/85, Art. 17, Inc. Final).'
        ]);

        // VIGÉSIMA SEGUNDA — Gastos (usar variables dinámicas)
        DB::table('contract_clauses')->where('id', 47)->update(['contenido' =>
            'Los gastos que cause este instrumento serán a cargo de {ARRENDATARIO} y {DEUDORES_SOLIDARIOS}.'
        ]);

        // VIGÉSIMA QUINTA — Copia del Contrato (agregar autorización de datos completa)
        DB::table('contract_clauses')->where('id', 50)->update(['contenido' =>
            'EL ARRENDATARIO manifiesta que ha recibido copia del presente contrato a satisfacción, con las firmas originales a la firma del presente documento, así como de la parte normativa del Reglamento de Propiedad Horizontal si es el caso. Parágrafo primero: Autorización de datos. Autorizo a LA INMOBILIARIA SERVIARRENDAR SAS para la recolección, almacenamiento y uso de mis datos personales con la finalidad de vincularme como cliente de INMOBILIARIA SERVIARRENDAR SAS. Autorizo el tratamiento de mis datos, incluso biométricos, que es un dato sensible, para los fines que sean necesarios para la prestación de los servicios encargados, particularmente para ejecutar y cumplir el contrato. Al momento de suscribir la presente autorización, me fue informada la información contractual existente entre los INMOBILIARIA SERVIARRENDAR SAS y por tanto autorizo a que esta última acceda nombre propio o de INMOBILIARIA SERVIARRENDAR SAS a las diferentes bases de datos y centrales de riesgo, antes las cuales haya acreditado poder para actuar, con las finalidades directas y propias del desarrollo del contrato. Autorizo a LA INMOBILIARIA SERVIARRENDAR SAS a entregar o compartir mi información con la finalidad de adelantar actividades y proyectos del sector asegurador; con Centrales de Información y Riesgo; con la finalidad de reportar los datos positivos o negativos de mi comportamiento crediticio y financiero. Como titular de la información tiene derecho a conocer, actualizar y rectificar sus datos personales, solicitar prueba de autorización otorgada para el tratamiento, revocar la autorización, solicitar la supresión de sus datos cuando sea procedente y acceder de forma gratuita a los mismos.'
        ]);

        // VIGÉSIMA SEXTA — Datos de Contacto (variables dinámicas completas)
        DB::table('contract_clauses')->where('id', 51)->update(['contenido' =>
            'Para efectos judiciales y extrajudiciales las partes se notificarán en las siguientes direcciones. Arrendador: {REP_LEGAL} a la dirección: {EMPRESA_DIRECCION} o al correo electrónico {EMPRESA_EMAIL}, número de celular {EMPRESA_CELULAR}. Arrendatario: {DIRECCION_ARRENDATARIO}. Deudor(es) solidario(s): {DIRECCION_DEUDORES}.'
        ]);

        // ══════════════════════════════════════════════════════════
        // TEMPLATE 3 — ARRENDAMIENTO COMERCIAL
        // ══════════════════════════════════════════════════════════

        // SEGUNDA — Destinación (agregar párrafo de usos ilícitos completo)
        DB::table('contract_clauses')->where('id', 53)->update(['contenido' =>
            'EL ARRENDATARIO se obliga a usar el inmueble para {DESTINACION}, su actividad comercial será {ACTIVIDAD_COMERCIAL} y no podrá darle otro uso, ni ceder o transferir el arrendamiento sin la autorización escrita del ARRENDADOR. El incumplimiento de esta cláusula dará derecho al ARRENDADOR para dar por terminado el contrato y exigir la entrega del inmueble o, en caso de cesión o subarriendo, celebrar un nuevo contrato con los usuarios reales, sin necesidad de requerimientos Judiciales o privados, a los cuales renuncia EL ARRENDATARIO. Parágrafo primero: EL ARRENDATARIO no destinará el inmueble a fines ilícitos, y en consecuencia se obliga a no utilizarlo para ocultar o depositar armas, explosivos o dineros de grupos terroristas o artículos de contrabando o para que en él se elaboren, almacenen o vendan drogas estupefacientes o sustancias alucinógenas y afines. EL ARRENDATARIO se obliga a no guardar o permitir que se guarden en el inmueble arrendado sustancias inflamables o explosivas que pongan en peligro la seguridad del mismo, y en caso que ocurriera dentro del inmueble enfermedad infectocontagiosa, serán del ARRENDATARIO los gastos de desafección que ordenen las autoridades sanitarias.'
        ]);

        // TERCERA — Pago (agregar párrafos completos)
        DB::table('contract_clauses')->where('id', 54)->update(['contenido' =>
            'EL ARRENDATARIO se obliga a pagar el valor acordado de forma anticipada, pagaderos dentro de los cinco (5) días de cada periodo mensual dentro de los plazos previstos, en la Oficina de Serviarrendar SAS, dirección carrera 13 No. 11 – 15, oficina 103 de Ocaña o a su orden, o en su defecto consignados en Bancolombia con el recibo de pago correspondiente. Parágrafo primero: EL ARRENDATARIO asumirá los costos de comisiones y notas débitos que se le descuenten a EL ARRENDADOR por cancelar su canon de arrendamiento desde otras plazas diferentes a Ocaña (Norte de Santander), transferencias, entre otros. Parágrafo segundo: La mera tolerancia de EL ARRENDADOR en aceptar el pago del precio del arrendamiento con posterioridad al plazo previsto para tal fin, no será suficiente para modificar las previsiones que al respecto han acordado las partes. Tampoco se consideran variadas las estipulaciones relativas al precio del arrendamiento por la recepción de pagos parciales. De conformidad con lo anterior, la aceptación de pagos parciales no invalidará los efectos que la mora produzca a cargo de EL ARRENDATARIO.'
        ]);

        // QUINTA — Mora (agregar párrafos completos)
        DB::table('contract_clauses')->where('id', 56)->update(['contenido' =>
            'La mora por falta de pago de la renta mensual en la oportunidad y forma acordada facultará al ARRENDADOR para hacer cesar el arriendo y exigir judicial o extrajudicialmente la restitución del bien, y presentar el respectivo cobro ejecutivo en contra de él y sus Coarrendatarios. Parágrafo primero: Si produce mora en el pago del precio del arrendamiento, EL ARRENDATARIO, además del canon o cánones debidos, reconocerá y pagará durante ella a EL ARRENDADOR el doble de los intereses moratorios calculados con la tasa máxima permitida para la mora en los créditos de libre consumo. Se hiciere en cheque y este resultare impagado EL ARRENDATARIO pagará, además, la sanción del veinte por ciento (20%) del valor del cheque, de conformidad con lo dispuesto en el artículo 731 del código de comercio. Todo lo anterior sin perjuicio de que EL ARRENDADOR pueda iniciar las acciones que, por incumplimiento, correspondan. Parágrafo segundo: Si el incumplimiento de la obligación de cancelar oportunamente los cánones de arrendamiento, servicios públicos, cuotas de administración o cualquier otra erogación derivada del contrato, diere lugar a alguna diligencia de cobro extrajudicial, EL ARRENDATARIO se obliga a pagar, como sanción moratoria por concepto de Gestión de Cobro una suma equivalente al diez por ciento (10%) de la suma adeudada. (Art. 1629 C. C.) — Dicha suma podrá ser exigida por la vía ejecutiva, sin perjuicio de las demás sanciones que por el incumplimiento o por mora se han pactado en este contrato y sin necesidad de requerimiento alguno.'
        ]);

        // SEXTA — Servicios (agregar párrafos completos + Línea Telefónica)
        DB::table('contract_clauses')->where('id', 57)->update(['contenido' =>
            'Están a cargo del ARRENDATARIO los servicios públicos de: {SERVICIOS}, y los siguientes servicios adicionales: especiales de telefonía, larga distancia, publicaciones en el directorio telefónico, internet, cuota de sostenimiento de T.V. Cable, cuota de sostenimiento de antena parabólica, cuota de administración de propiedad horizontal o celaduría, con los incrementos que al respecto decrete la Asamblea de copropietarios, y pagados directamente por EL ARRENDATARIO sin que el ARRENDADOR tenga responsabilidad alguna por la correcta o deficiente prestación de tales servicios. Parágrafo primero: EL ARRENDATARIO se obliga a pagar las sanciones, costos y multas que las Empresas de Acueducto, Energía Eléctrica, Teléfono, Gas o cualquier otra Autoridad, Empresa, Juntas Comunales y Juntas Administradoras de los condominios del Régimen de Propiedad Horizontal impongan, durante la vigencia del presente contrato por las infracciones de los respectivos reglamentos o por no haber pagado oportunamente tales servicios e indemnizará AL ARRENDADOR por los perjuicios que pudieran tener por tales infracciones u omisiones. Es entendido que EL ARRENDADOR puede, si lo considera conveniente, hacer las respectivas cancelaciones para obtener la normalización de los mencionados servicios, así como también podrá pagar las sanciones, impuestos y multas, y en estos casos su costo deberá ser reembolsado en forma inmediata por EL ARRENDATARIO, pudiendo ser cobrado por la vía ejecutiva, sin necesidad de requerimiento alguno, con la simple presentación de los respectivos recibos, debidamente cancelados. Parágrafo segundo: Línea Telefónica. Se deja expresa constancia que el inmueble se arrienda SIN LÍNEA TELEFÓNICA. Si durante la vigencia de este contrato se instalare en el inmueble arrendado una o más líneas telefónicas EL ARRENDATARIO junto con sus DEUDORES SOLIDARIOS se comprometen al pago del servicio telefónico correspondiente y a retirar a la terminación del Contrato de Arrendamiento las líneas adicionales que se le hayan autorizado posteriormente a la firma del presente contrato.'
        ]);

        // SÉPTIMA — Cobro Extrajudicial (agregar párrafo ASEGURADORA)
        DB::table('contract_clauses')->where('id', 58)->update(['contenido' =>
            'Si el incumplimiento de la obligación de cancelar oportunamente los cánones de arrendamiento, cuotas de administración, servicios públicos, celaduría y/o vigilancia así como cualquier otra erogación derivada del presente contrato, diere lugar a alguna diligencia de cobro extrajudicial, EL ARRENDATARIO y sus DEUDORES SOLIDARIOS se obligan a pagar a la entidad encargada de tal gestión los costos que ello genere (Gestión de cobro, intereses, carta de recordatorio de canon y honorarios), ello en razón a que los gastos que ocasione la obtención del pago son de cuenta de los deudores; lo anterior sin perjuicio de lo estipulado por la casa de cobranza, gestor jurídico, entidad aseguradora o afianzadora en sus manuales de cobranza, y aquello que el juez ordenare acerca de las costas judiciales, conforme disposición expresa del artículo 1629 del Código Civil. Parágrafo: El ARRENDATARIO y los DEUDOR(ES) SOLIDARIO(S) manifiestan conocer y aceptar desde ahora, la póliza de seguro de arrendamiento expedida por la compañía ASEGURADORA elegida por el ARRENDADOR, así como las sumas de dinero que eventualmente se llegaran a causar como indemnización a favor de el arrendador con ocasión del incumplimiento de las obligaciones pactadas en el presente contrato de arrendamiento. En el evento en que la ASEGURADORA indemnice el incumplimiento de las obligaciones dinerarias derivadas del presente contrato, EL ARRENDATARIO y los DEUDOR(ES) SOLIDARIO(S) se obligan a: (1) Pagar y reconocer a favor de la compañía ASEGURADORA las sumas que este último llegue a pagar a favor de EL ARRENDADOR como resultado del incumplimiento, entendiendo que ha operado una subrogación legal de todos los derechos, acciones y privilegios, en los términos de los artículos 1036 y s.s. del Código de Comercio, art. 1096 de la misma fuente normativa, arts. 1666 a 1671 del Código Civil y demás normas concordantes. (2) Pagar y reconocer honorarios de cobranza, en etapa judicial y extrajudicial de las sumas adeudadas, así como las ocasionadas por el proceso de restitución del inmueble que se adelante en contra de EL ARRENDATARIO.'
        ]);

        // OCTAVA — Recibo y Estado (agregar pintura y 15%)
        DB::table('contract_clauses')->where('id', 59)->update(['contenido' =>
            'EL ARRENDATARIO declara que ha recibido el inmueble objeto de este contrato en buen estado, conforme al inventario que se adjunta, el cual hace parte de este contrato, y en el mismo se determinan los servicios, cosas y usos conexos y adicionales. EL ARRENDATARIO a la terminación del contrato, deberá devolver al ARRENDADOR el inmueble en el mismo estado de funcionamiento, todo lo cual consta en el referido anexo, salvo el deterioro proveniente legítimo, y/o EL ARRENDATARIO hará cancelación de los daños ocasionados. EL ARRENDATARIO se obliga a conservarlo y restituirlo en las mismas condiciones, especialmente en lo referente a la pintura general del inmueble. Por medio de la firma de este contrato se compromete a entregarlo nuevamente pintado o en sus defecto autoriza para que EL ARRENDADOR efectúe dicha obra asumiendo EL ARRENDATARIO los costos de la misma. Para este efecto convienen las partes que las facturas de reparación de daños, de obra de pintura o de reposición de faltantes junto con el contrato de arrendamiento prestan mérito ejecutivo suficiente y adicionalmente EL ARRENDATARIO cancelará el 15% adicionalmente a EL ARRENDADOR sobre el valor de la obra ejecutada, a la terminación del arrendamiento, o cuando este haya de cesar por alguna de las causales previstas, salvo el deterioro proveniente del tiempo y del uso legítimo.'
        ]);

        // NOVENA — Mejoras (agregar párrafos completos)
        DB::table('contract_clauses')->where('id', 60)->update(['contenido' =>
            'EL ARRENDATARIO tendrá a su cargo las reparaciones locativas a que se refiere la ley (C.C. Arts. 2028, 2029 y 2030) y no podrá realizar otras sin el consentimiento escrito del ARRENDADOR. En todo caso, EL ARRENDATARIO podrá retirar las mejoras y/o reformas introducidas en el inmueble, siempre y cuando se pueda proceder a ello sin detrimento del inmueble; en caso contrario, las mejoras quedarán de propiedad de EL ARRENDADOR, quien no estará obligado a reconocer, por tal concepto, suma alguna a favor de EL ARRENDATARIO si se ejecutaren accederán al propietario del inmueble sin indemnización para quien las efectuó. EL ARRENDATARIO renuncia expresamente a descontar de la renta el valor de las reparaciones indispensables, a que se refiere el artículo 27 de la Ley 820 de 2003. Parágrafo Primero: Si EL ARRENDATARIO por alguna circunstancia efectuara mejoras en el inmueble objeto de este contrato de arrendamiento, no obstante la prohibición contenida en esta cláusula y tales mejoras a juicio del ARRENDADOR constituyeran una depreciación para el inmueble, EL ARRENDATARIO se obliga a retirarlas y a entregar el bien en el estado en lo recibió. Si no diere cumplimiento a dicha obligación, la depreciación del inmueble será estimada parcialmente y su valor será exigible por la vía ejecutiva. Parágrafo segundo: Mejoras Locativas. Las reparaciones locativas serán a cargo de EL ARRENDATARIO, quien deberá proceder a ellas de inmediato y sin necesidad de que medie autorización de EL ARRENDADOR. Se entiende por reparaciones locativas aquellas que deben hacerse para arreglar los deterioros que ordinariamente se producen por culpa de EL ARRENDATARIO o de sus dependientes, como, por ejemplo, descalabros de paredes, rotura de cristales, etc.'
        ]);

        // DÉCIMA SEGUNDA — Deudor Solidario (texto completo con variables)
        DB::table('contract_clauses')->where('id', 63)->update(['contenido' =>
            '{DEUDORES_SOLIDARIOS}, nos declaramos deudores solidarios de {ARRENDATARIO}, en forma solidaria e indivisible, en todas las cargas y obligaciones contenidas en el presente contrato, tanto y durante el término inicialmente pactado como durante sus prórrogas o renovaciones expresas o tácitas y hasta que se produzca la entrega material del inmueble al ARRENDADOR, por concepto de arrendamiento, servicios públicos indemnizaciones, daños en el inmueble, cuotas de administración, intereses moratorios, honorarios causados en caso de mora en el pago del arriendo por las gestiones de cobranza extrajudicial o judicial y las costas procesales a que sea condenado EL ARRENDATARIO en la cuantía señalada por el respectivo juzgado en el caso del proceso de restitución, cláusulas penales etc., las cuales podrán ser exigidas por EL ARRENDADOR a cualquiera de las obligaciones por la vía ejecutiva, sin necesidad de requerimientos privados o judiciales a los cuales renunciamos expresamente, sin que por razón de esta solidaridad asumamos el carácter de fiadores ni arrendatarios. Para este exclusivo efecto EL ARRENDATARIO otorga poder amplio y suficiente a los DEUDORES SOLIDARIOS en este mismo acto y al suscribirse el presente contrato.'
        ]);

        // DÉCIMA TERCERA — Cesión de Contrato (texto completo)
        DB::table('contract_clauses')->where('id', 64)->update(['contenido' =>
            '{DEUDORES_SOLIDARIOS}, como deudor(es) solidario(s) acepto(amos) expresamente desde ahora cualquier cesión que EL ARRENDADOR haga respecto del presente contrato y ratificamos nuestra voluntad de que la notificación de que trata el artículo 1960 del Código Civil se surta con el solo envío de la nota de cesión acompañada de copia simple del contrato, por servicio postal autorizado, a la dirección que aparece registrada en este contrato al pie de nuestras respectivas firmas.'
        ]);

        // DÉCIMA QUINTA — Obligaciones (ampliar con referencias Código de Comercio)
        DB::table('contract_clauses')->where('id', 66)->update(['contenido' =>
            'Son obligaciones de las partes las siguientes: a) Del ARRENDADOR: 1. Entregar al ARRENDATARIO en la fecha convenida el inmueble dado en arrendamiento en buen estado de servicio, seguridad y sanidad y poner a su disposición los servicios, cosas o usos conexos y los adicionales aquí convenidos. 2. Mantener en el inmueble los servicios, las cosas y los usos conexos y adicionales en buen estado de servir para el fin convenido en el contrato. 3. Entregar al ARRENDATARIO una copia del reglamento interno de propiedad horizontal al que se encuentra sometido el inmueble (ello cuando el inmueble arrendado esté sometido a dicho régimen). 4. Las demás obligaciones consagradas para las partes en el Código de Comercio (Artículos 518 a 524 y concordantes), y de forma supletoria por lo dispuesto en el Código Civil (Libro 4, Título XXVI). b) Del ARRENDATARIO: 1. Pagar al ARRENDADOR en el lugar convenido en la cláusula tercera del presente contrato, el precio del arrendamiento. En el evento que EL ARRENDADOR rehúse recibir en las condiciones y lugar aquí acordados, EL ARRENDATARIO podrá efectuarlo mediante consignación a favor del ARRENDADOR en las instituciones autorizados por el Gobierno Nacional para tal efecto de acuerdo con el procedimiento legal vigente. 2. Cuidar el inmueble y las cosas recibidas en arrendamiento. En caso de daños o deterioros distintos derivados del uso normal o de la acción del tiempo y que fueren imputables al mal uso del inmueble a su propia culpa, efectuar oportunamente y por su cuenta las reparaciones o sustituciones necesarias. 3. Cumplir con las normas consagradas en el reglamento de propiedad horizontal al que se encuentra sometido el inmueble arrendado (ello cuando el mismo esté sometido a dicho régimen), así como las demás disposiciones que dicte el Gobierno Nacional dirigidas a la protección de los derechos de todos los vecinos. 4. Las demás obligaciones consagradas para el ARRENDATARIO en el Código de Comercio (especialmente en lo referente a la conservación del establecimiento y el derecho de renovación, Artículos 518 a 524) y, de manera supletoria, las contenidas en el Capítulo III, Título XXVI, Libro 4 del Código Civil.'
        ]);

        // DÉCIMA SEXTA — Terminación (ampliar causales)
        DB::table('contract_clauses')->where('id', 67)->update(['contenido' =>
            'Son causales de terminación del contrato en forma unilateral, las consagradas en el Código de Comercio especialmente los artículos 518 a 524. Además, se da por terminado este contrato también si se realiza: a) La cesión o subarriendo b) El cambio de destinación del inmueble c) El no pago del precio dentro del término previsto en este contrato d) La destinación del inmueble para fines ilícitos o contrario a las buenas costumbres, o que representen peligro para el inmueble o la salubridad de sus habitantes e) La realización de mejoras, cambios o ampliaciones del inmueble, sin expresa autorización del ARRENDADOR f) La no cancelación oportuna de los servicios públicos a cargo del ARRENDATARIO g) La no cancelación del valor de las cuotas de administración, dentro de los términos pactados h) Cuando el ARRENDATARIO viole las normas del respectivo reglamento interno o de propiedad horizontal, o no pague las expensas comunes cuando el pago esté a su cargo i) Cuando el propietario o poseedor necesite el inmueble para ocuparlo, o cuando el inmueble haya de demolerse para efectuar una nueva construcción, o cuando se requiera desocuparlo con el fin de ejecutar obras indispensables para su reparación j) Cuando el inmueble haya de entregarse en cumplimiento de las obligaciones originadas en un contrato de compraventa k) Y demás previstas en la Ley.'
        ]);

        // DÉCIMA OCTAVA — Preaviso (corregir: indemnización = 3 meses, no 6)
        DB::table('contract_clauses')->where('id', 69)->update(['contenido' =>
            'EL ARRENDADOR podrá dar por terminado el contrato de arrendamiento durante cualquiera de sus prórrogas, mediante preaviso dado al ARRENDATARIO con seis (6) meses de anticipación. Así mismo, EL ARRENDATARIO podrá dar por terminado unilateralmente el contrato de arrendamiento dentro del término inicial o el de sus prórrogas previo aviso escrito al ARRENDADOR, con un plazo no menor de seis (6) meses y el pago de una indemnización equivalente al precio de tres (3) meses de arrendamiento. Cumplidas estas condiciones EL ARRENDADOR estará obligado a recibir el inmueble; si no lo hiciere, EL ARRENDATARIO podrá hacer entrega provisional mediante la intervención de la autoridad administrativa competente, sin perjuicio de acudir a la acción judicial correspondiente. Parágrafo primero: No habrá lugar a la indemnización si el aviso de terminación por parte del ARRENDATARIO se refiere al término estipulado en este contrato (Código de Comercio).'
        ]);

        // VIGÉSIMA PRIMERA (Gastos) — usar variables dinámicas
        DB::table('contract_clauses')->where('id', 77)->update(['contenido' =>
            'Los gastos que cause este instrumento serán a cargo de {ARRENDATARIO} y {DEUDORES_SOLIDARIOS}.'
        ]);

        // VIGÉSIMA QUINTA — Copia del Contrato (agregar autorización datos)
        DB::table('contract_clauses')->where('id', 76)->update(['contenido' =>
            'EL ARRENDATARIO manifiesta que ha recibido copia del presente contrato a satisfacción, con las firmas originales a la firma del presente documento, así como de la parte normativa del Reglamento de Propiedad Horizontal si es el caso.'
        ]);

        // VIGÉSIMA SEXTA — corregir: título="Autorización de datos", contenido=texto autorización
        DB::table('contract_clauses')->where('id', 78)->update([
            'titulo'    => 'Autorización de datos',
            'contenido' => 'Autorizo a LA INMOBILIARIA SERVIARRENDAR SAS para la recolección, almacenamiento y uso de mis datos personales con la finalidad de vincularme como cliente de INMOBILIARIA SERVIARRENDAR SAS. Autorizo el tratamiento de mis datos, incluso biométricos, que es un dato sensible, para los fines que sean necesarios para la prestación de los servicios encargados, particularmente para ejecutar y cumplir el contrato. Al momento de suscribir la presente autorización, me fue informada la información contractual existente entre los INMOBILIARIA SERVIARRENDAR SAS y por tanto autorizo a que esta última acceda nombre propio o de INMOBILIARIA SERVIARRENDAR SAS a las diferentes bases de datos y centrales de riesgo, antes las cuales haya acreditado poder para actuar, con las finalidades directas y propias del desarrollo del contrato. Autorizo a LA INMOBILIARIA SERVIARRENDAR SAS a entregar o compartir mi información con la finalidad de adelantar actividades y proyectos del sector asegurador; con Centrales de Información y Riesgo; con la finalidad de reportar los datos positivos o negativos de mi comportamiento crediticio y financiero. Como titular de la información tiene derecho a conocer, actualizar y rectificar sus datos personales, solicitar prueba de autorización otorgada para el tratamiento, revocar la autorización, solicitar la supresión de sus datos cuando sea procedente y acceder de forma gratuita a los mismos.',
        ]);

        // VIGÉSIMA SÉPTIMA — corregir: título="Datos de Contacto", contenido con variables
        DB::table('contract_clauses')->where('id', 79)->update([
            'titulo'    => 'Datos de Contacto',
            'contenido' => 'Para efectos judiciales y extrajudiciales las partes se notificarán en las siguientes direcciones. Arrendador: {REP_LEGAL} a la dirección: {EMPRESA_DIRECCION} o al correo electrónico {EMPRESA_EMAIL}, número de celular {EMPRESA_CELULAR}. Arrendatario: {DIRECCION_ARRENDATARIO}. Deudor(es) solidario(s): {DIRECCION_DEUDORES}.',
        ]);
    }

    public function down(): void
    {
        // No se implementa rollback de contenido — restaurar desde respaldo si es necesario
    }
};
